
//
//  AAAA.h
//  iShare
//
//  Created by Jin Jin on 12-8-5.
//  Copyright (c) 2012年 Jin Jin. All rights reserved.
//

#define NOTIFICATION_FILEBROWSER_MENUSHOWN @"NOTIFICATION_FILEBROWSER_MENUSHOWN"
#define NOTIFICATION_FILEBROWSER_MENUGONE @"NOTIFICATION_FILEBROWSER_MENUGONE"

#define NOTIFICATION_FILEBROWSER_DELETEBUTTONCLICKED @"NOTIFICATION_FILEBROWSER_DELETEBUTTONCLICKED"
#define NOTIFICAITON_FILEBROWSER_OPENINBUTTONCLICKED @"NOTIFICAITON_FILEBROWSER_OPENINBUTTONCLICKED"
#define NOTIFICATION_FILEBROWSER_MAILBUTTONCLICKED @"NOTIFICATION_FILEBROWSER_MAILBUTTONCLICKED"
#define NOTIFICATION_FILEBROWSER_RENAMEBUTTONCLICKED @"NOTIFICATION_FILEBROWSER_RENAMEBUTTONCLICKED"
#define NOTIFICATION_FILEBROWSER_ZIPBUTTONCLICKED @"NOTIFICATION_FILEBROWSER_ZIPBUTTONCLICKED"